# Generated by Django 4.2.1 on 2023-09-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('name_manager', models.CharField(max_length=50)),
                ('email_manager', models.EmailField(max_length=254)),
                ('id_realty', models.IntegerField()),
            ],
        ),
    ]
