# Generated by Django 4.2.1 on 2023-09-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRealty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_realty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover_image', models.ImageField(upload_to='cover_image')),
                ('s', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('info', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('active', models.BooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realty.city')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realty.house')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.manager')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realty.street')),
                ('type_realty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realty.typerealty')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_image')),
                ('realty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='realty.realty')),
            ],
        ),
    ]
