# Generated by Django 4.2.1 on 2023-09-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
